apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-applicationset
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: ''
  source:
    path: ''
    repoURL: ''
    targetRevision: HEAD
  project: ''
  generators:
    - list:
        elements:
          - env: qa
          - env: staging
          - env: prod
  template:
    metadata:
      name: '{{env}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/nielsdeen1/gitops-cert-level-2-examples/'
        targetRevision: HEAD
        path: './environment-promotion/envs/{{env}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
